Zarmada/working/ADTS-172
microsoft/iot-cardboard-js pull request #535
Opened 2022-06-07 20:21 UTC by miltonzarmada

### Summary of changes 🔍 
Adding models should be in the graph view

### Testing 🧪
 > [ Add any special instructions needed to test or view your changes such as environment URLs or other config details. ]

### Checklist ✔️
- [ ] Linked associated issue (if present)
- [ ] Added relevant labels
- [ ] Requested developer reviews
- [ ] Request UI review from design / PM
- [ ] Verify all code checks are passing

2022-06-07 20:48 UTC, jamescarpinter requested changes

2022-06-07 20:48 UTC, jamescarpinter commented on src/Components/OATGraphViewer/OATGraphViewer.tsx
> +const zoomOnNewNodeCreation = 1.2;
Can we try to leave the zoom at the current level?

2022-06-13 18:39 UTC, miltonzarmada commented
@jamescarpinter addressed feedback

2022-06-13 18:45 UTC, jamescarpinter requested changes

2022-06-13 18:45 UTC, jamescarpinter commented on src/Components/OATGraphViewer/OATGraphViewer.tsx
> +                    wrapperBoundingBox.height / 2,
So `x` considers the `nodeWidth` but `y` doesn’t? Shouldn’t it consider `nodeHeight / 2`?

2022-06-14 17:32 UTC, jamescarpinter approved these changes

2022-06-14 17:32 UTC, merged